name: PR has a valid Issue?

on:
  pull_request:
    types: [labeled]

jobs:
  checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: ./.github/actions/PR_has_a_valid_issue/
        with:
          pr_body: "${{ github.event.pull_request.url }}"

      - name: prints PR body
        # github.event.pull_request.url to get the body of the PR
        run: echo "XZANATOL this is ${{ github.event.pull_request.url }}"
