name: PR has a valid Issue?

on:
  pull_request:
    types: [ edited, synchronize, opened, reopened ]

jobs:
  checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: "Issue number validator"
        uses: ./.github/actions/PR_has_a_valid_issue/
        id: validator
        with:
          prbody: ${{ github.event.pull_request.body }}
          prurl: ${{ github.event.pull_request.url }}

      - name: "Validation action on 1"
        if: ${{ steps.validator.outputs.valid == 1 }}
        run: |
          echo $Github_Token > mytoken.txt
          gh auth login --with-token < mytoken.txt
          gh pr edit $PRNUM --add-label "Ready_to_Review"
          rm mytoken.txt
        env:
          Github_Token: ${{ secrets.GITHUB_TOKEN }}
          PRNUM: ${{ github.event.pull_request.number }}

      - name: "Validation action on 0"
        if: ${{ steps.validator.outputs.valid == 0 }}
        run: gh pr comment $PRNUM --body "Please update PR body with a valid issue number"
        env:
          PRNUM: ${{ github.event.pull_request.number }}
