name: PR has a valid Issue?

on:
  pull_request:
    types: [labeled]

jobs:
  checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: "Pull request body displayer"
        uses: ./.github/actions/PR_has_a_valid_issue/
        with:
          prbody: ${{ github.event.pull_request.body }}
          prurl: ${{ github.event.pull_request.url }}

      - name: prints PR url
        run: echo "XZANATOL this is $body"
        env:
          body: ${{ github.event.pull_request.body }}
