name: PR has a valid Issue?

on:
  pull_request:
    types: [labeled]

jobs:
  checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: "Issue number validator"
        uses: ./.github/actions/PR_has_a_valid_issue/
        id: validator
        with:
          prbody: ${{ github.event.pull_request.body }}
          prurl: ${{ github.event.pull_request.url }}

      - name: "Validation variable viewer"
        run: echo ${{ steps.validator.outputs.valid }}
