name: PR has a valid Issue?

on:
  pull_request:
    types: [labeled]

jobs:
  checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: "Pull request body displayer"
        uses: ./.github/actions/PR_has_a_valid_issue/
        with:
          prbody: "$github.event.pull_request.body"

      - name: prints PR url
        # github.event.pull_request.body to get the body of the PR
        run: echo "XZANATOL this is ${{ github.event.pull_request.url }}"
