name: PR has a valid Issue?

on:
  pull_request:
    types: [ edited, synchronize, opened, reopened ]

jobs:
  checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: PR_has_a_valid_issue
        uses: XZANATOL/prepare-to-publish-github-action@3
        with:
          prbody: ${{ github.event.pull_request.body }}
          prurl: ${{ github.event.pull_request.url }}
          message: "Please Enter a valid issue"
          invlbl: "bug"
          vlbl: "documentation"
          token: ${{ secrets.GITHUB_TOKEN }}
