name: Python package

on:
  pull_request:
    types: [labeled]

jobs:
  extract_and_update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'

      - name: Run script
        run: |
          python -m pip install –upgrade pip
          pip install PyGithub
          python ./.github/scripts/Update_Database.py "$body" "$token"
        env:
          body: ${{ github.event.pull_request.body }}
          token: ${{ secrets.github_token }}
