name: PR has a valid Issue?

on:
  pull_request:
    types: [labeled]

jobs:
  checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: "Issue number validator"
        uses: ./.github/actions/PR_has_a_valid_issue/
        id: validator
        with:
          prbody: ${{ github.event.pull_request.body }}
          prurl: ${{ github.event.pull_request.url }}

      - name: "Validation action on 1"
        uses: actions/labeler@v2
        if: ${{ steps.validator.outputs.valid == 1 }}
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeller.yml

      - name: "Validation action on 0"
        if: ${{ steps.validator.outputs.valid == 0 }}
        run: gh pr comment $PRNUM --body "Please update PR body with a valid issue number"
        env:
          PRNUM: ${{ github.event.pull_request.number }}
